Layout/Tab:
  Enabled: false
Layout/IndentationWidth:
  Width: 1
Layout/IndentArray:
  EnforcedStyle: consistent
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

AllCops:
  TargetRubyVersion: 2.3
